spring.profiles: dev
server.port: 8080
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
  application:
    name: iOrc-API 0.0.01T
---
spring.profiles: production
server.port: 8081
spring:
  data:
    mongodb:
      uri: mongodb://<UNAME>:<PASSWORD>@cluster0-shard-00-00-htx90.mongodb.net:27017,cluster0-shard-00-01-htx90.mongodb.net:27017,cluster0-shard-00-02-htx90.mongodb.net:27017/test?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin
  application:
    name: iOrc-API 0.0.01b